### ISSUE TITLE
Logging responses

### ISSUE THREAD

**Issue by CG-root** [drk1wi/Modlishka#134]
If I want to make a phishing for a specific system, I would have to get the session cookie from the response sent from the original server.
Is it possible to add logging to responses as well?

**Comment by drk1wi** [comment]
That's actually really easy, but I guess it would only make sense to log response headers.
Another challenge it to actually track all of the cookies properly (you can check out my initial attempt in the 'control' plugin), which sometimes might be tricky.

**Comment by CG-root** [comment]
Is it possible to have an output in JSON format of all cookies just like in Evilginx?
I mean, I have tried to use custom login and inserted right credentials but I don't get nothing in "Collected user credentials" screen.

**Comment by CG-root** [comment]
I mean, isn't there a way to make it more generic?
like if the user successfully authenticated and and new cookies are set. can we grab these cookies and impersonate with them?

**Comment by drk1wi** [comment]
It is possible to create a JSON output, it's just a matter of changing the output in the 'control' panel plugin. The reason why you didn't get any credentials is because there was no user identifier set - this could be improved and done automatically to mark all users on entry to the proxy. Just a matter of some extra coding. 
Impersonation plugin requires some further work to be truly generic for all cases, including cookies set by the JS though.

**Comment by CG-root** [comment]
I mean, if I try to phish some custom vpn, I don't know what will be the name of the cookie, but is it important?
I mean, once we detected that the user inserted credentials and a new cookie was set, I can use the cookie to perform impersonation, is that correct?
I mean, why is it important to set the cookie name beforehand?

**Comment by drk1wi** [comment]
In the log file, Cookies should be logged. Look for nCOOKIES entry.
