### ISSUE TITLE
cloudflare Modlishka not work

### ISSUE THREAD

**Issue by crabscore** [drk1wi/Modlishka#158]
cloudflare is used on the site when entering loopback.moodlishka.com there is a constant page refresh and the entry is not performed, how can this be solved? Is there an exact example?

**Comment by ad0nis** [comment]
@crabscore: `loopback.modlishka.io` is an example domain used in the config files. You must provide a domain name you control in that field in place of that example. If you're hitting cloudflare for that domain, it's likely because the controller of it had their DNS records pointing at something in cloudflare.

@drk1wi: recommend closing this issue as a non-issue, unless if there are other known issues with modlishka and cloudflare.

**Comment by Gta0147** [comment]
his kinda correct cause it seems cloudflare is blocking somthing which am yet to figure out
