### ISSUE TITLE
Some errors (Need Help) 

### ISSUE THREAD

**Issue by abouhad** [drk1wi/Modlishka#162]
Hey! 
1.I have created a wildcard record. with _acme-challenge.domain.com and TXT string.
How can I modify the subdomain to be more credible? 

2.My SSL it's only supported on *.domain.com, I need to add the root domain to Wildcard Certificate?

3.At the end of my domain example.com/SayHello2Modlishka it doesn't appear anything

4.How can I add the post value of username & password of the tricking page.The text it's encrypted in base64? for example if the value it's username i must encode username to base64?

**Comment by ad0nis** [comment]
@abouhad
1. The _acme-challenge DNS record is only used by letsencrypt to prove that you have authority over that DNS name. This record should not be used at any point in your campaign, and shouldn't be viewable by the end-user unless if they start doing basic DNS lookups on your domain. You can make this domain as credible as your imagination allows if your wildcard record is setup correctly. Some.super.legit.looking.subdomain.whatever-domain-you-own.tld for example. You just need to then configure this subdomain as the domain modlishka uses.

2. That's really a question of how you'd like the campaign to appear and what URLs you'll be using. If anyone will be landing on the base domain, then yeah, include it. If not, then don't.

3. Make sure that modlishka is actually the webserver that your requests are landing on. Consider trying alternative "-controlURL string" option instead of the default as an alternative test.

4. This is actually a solid question, as I've tried several formats based on the documentation without success, and am awaiting a response in #213 .
