### ISSUE TITLE
Control panel database is overwritten every time credentials are captured

### ISSUE THREAD

**Issue by robloxspoof** [drk1wi/Modlishka#175]
**Describe the bug**
Control panel database is overwritten every time credentials are captured. Only one cred shows at a time. The credentials are correct, however.

**Expected behavior**
It should instead list all at the same time

**Configuration (please complete the following information):**
 - "credParams": "dXNlcm5hbWU9KFteXFddKyk=,cGFzc3dvcmQ9KFteXFddKyk="

**Comment by DakotaNelson** [comment]
You need to include a `trackingParam` so that the credentials can be uniquely identified. Since the credentials are coming in with a "tracking parameter" of `""` (e.g. no tracking parameter at all) they're all being treated as the same tracking parameter (again - the "null" tracking parameter) and being overwritten.

That said, I do think this is a case of unintended behavior; is it possible to capture all credentials that come in without a tracking UUID by assigning them a "dummy" UUID? I suspect this would save a lot of confusion down the road.

For that matter, if a user enters several sets of credentials while in the same (proper, with UUID) session, it would be good to have all of those sets of credentials in that case as well instead of overwriting old creds. I've been on engagements where users enter several sets of (valid) credentials in confusion, it would be a shame to throw any away.

**Comment by DakotaNelson** [comment]
Ah - see #33, my bad 😛
