### ISSUE TITLE
Link takes me to router login page

### ISSUE THREAD

**Issue by thehotdogmustard** [drk1wi/Modlishka#189]
**Describe the bug**

I registered a domain over at [porkbun.com](url) and added an A record for my public IP and a CNAME wildcard record.

These are the records bellow:

A RECORD:
HOST: somedomain.com ANSWER: XXX.XXX.XXX.XXX

CNAME RECORD:
HOST: *.somedomain.com ANSWER: www.somedomain.com

After making those records, I had to issue a certificate with acme.sh for my domain.

I used the command below:

`acme.sh --issue -d somedomain.com -d '*.somedomain.com' --dns --yes-I-know-dns-manual-mode-enough-go-ahead-please`

The certificate and key I implemented into autocert.go file as specified in the wiki.

After that I launched the modlishka tool using the command:

`./dist/proxy -config templates/google.com_gsuite.json`

The listening address is 0.0.0.0 and two ports (443 and 80) were used for HTTPS and HTTP protocol.

Once I clicked on the https link I was redirected to my router login page.
I am not sure why this is so, but I tried opening the site on other devices on my network and it doesn't work.

**Comment by ad0nis** [comment]
@thehotdogmustard: This sounds like an issue with your home network configuration or NAT or port forwarding rules, and not an issue with Modlishka itself. Your devices from inside your home network (behind NAT) are likely being directed to your public IP if your DNS records were setup properly, and then I'm guessing that your network is routing that IP to its own admin panel instead of to whatever internal server you're intending to port forward. 

To troubleshoot, use another system outside of your network, such as a VPS (or even your phone, over a cellular connection) and see what you see when you connect to your chosen domain name. Depending on how things are setup on your side, I predict that you'll likely either see your modem control panel (which would be bad, as it means you've exposed it to the public internet), or you'll actually get the modlishka server you expect if your port forwarding is actually working properly. If neither of these happen, then your port forwarding is not configured properly.

@drk1wi: Recommend closing this issue, as it's clearly not an issue in Modlishka, but something specific to the poster's network configuration.
