### ISSUE TITLE
Few issues

### ISSUE THREAD

**Issue by hulapolowashed** [drk1wi/Modlishka#213]
Only can catch username and password in log file and they always have text around them it looks like h8oe239k393eifr938g59j849j4gt9&MYUSERNAMEvjivvonv93ft9nvcvn%onvMYPASSWORD
Not exact I just made that up without looking at log file this moments but similar I think because of this is why I can't catch credentials in panel. I try different regex no change.

It is not possible to have a link parked waiting for clicks if each link needs UUID appended to the end otherwise credentials only go to log file which become harder to extract, each visit to the link should create a record in the panel even if it has no UUID.

How to get old impersonate use button back in control panel?

JsRULES are very hard to complete and there is little documentation anywhere if you want to replace a random string of numbers or characters on the website with your own random string how can this be done easily?

**Comment by drk1wi** [comment]
it's regular expression. If you want to extract password or usernames (or other info) it's best to use https://regex101.com/ and work on the relevant HTTP requests payloads.

**Comment by ad0nis** [comment]
@drk1wi: If I'm not mistaken, the use of regular expressions within modlishka currently appears to be broken. I've used a test expression based off the example from the docs, and have been unable to get a successful credential parse out of the tool thus far. Here is my example from my test json file, which I ran through the regex tester you linked above:
`
  "credParams": "dXNlcm5hbWU9KFteXFddKylcJg==,cGFzc3dvcmQ9KFteXFddKylcJg==",
`
If I base64 decode those two expressions, they are the following:

`
username=([^\W]+)\&
`
`
password=([^\W]+)\&
`

The credentials are being submitted to the application in the following format according to verbose modlishka logs:
`
username=admin&password=demo&s_mod=login&s_pg=index
`

If I take those expressions and that example submission and run them through regex101, they get detected correctly, but modlishka control panel shows no test usernames or passwords. I've also tested the same expression with an escaped '=' symbol as well as with both '=' and '&' symbols un-escaped. In none of those three situations does modlishka correctly apply a regular expression.

If they are believed to be currently functional, can you please provide a working sample regular expression and a demo site that it works against for confirmation?

**Comment by ad0nis** [comment]
So I finally got this working, but it took some additional testing and debugging. The format that I thought the credentials were coming in as changed at some point while I was testing, and I had missed it. 😅 (Testing against services you don't control is a bad idea, folks. 😄 ) Regexes that finally worked for me were as follows, for anyone else running into trouble with this. (Which seems like a lot of people, considering how many bugs I found and tagged to this one that appeared to be identical.)

For a credential submission in the following format:
`
actionID=&hdnUserTimeZoneOffset=-4&installation=&_csrf_token=csrftokenhere&txtUsername=admin&txtPassword=password&Submit=LOGIN
`
The following base64-encoded regexes should work correctly:
`
  "credParams": "dHh0VXNlcm5hbWVcPSguKilcJnR4dFBhc3N3b3Jk,dHh0UGFzc3dvcmRcPSguKilcJlN1Ym1pdD1MT0dJTg==",
`
Those can be generated with an example like this:
```
echo -n "txtUsername\=(.*)\&txtPassword" | base64
echo -n "txtPassword\=(.*)\&Submit=LOGIN" | base64
```

@drk1wi: To help make this feature easier for operators to interact with, would it make sense to store all submitted POST variables instead of only the selected ones, and to make them available on a button just like the cookies are, and then have the username and password fields pull from a dictionary of common username and password variable names which can be expanded upon as necessary to support additional platforms, but would automatically support platforms where the username and password field are literally named username and password?
