### ISSUE TITLE
Drk1wi READ PLEASE

### ISSUE THREAD

**Issue by hulapolowashed** [drk1wi/Modlishka#219]
You said no time to work on tool now but please help answer 2 question, we can not work these ones out.

1. replacing content on a webpage. Content can be random string on letters/number or a phrase how can this be replaced using target rules? Example if string is hellothisismycodehello and we want to replace with 12345678910 what is code to do this?

2. We find one strange site we test where the name of the username and login field change each refresh and look like rgvh9oeror9wkkloe after refresh changes, is there currently way to catch the credentials of site like this?

**Comment by drk1wi** [comment]
1/changing this should be easy, since this can be done with regex groups. Right now the target 'rules' parameter only accepts 
static replacements. similar thing is done  in the credentials regex (it's a regex group).
2/you need to create a regex pattern with a matching group that will pin point the right string. try this https://regex101.com/

**Comment by hulapolowashed** [comment]
Thanks drk1wi we tried a few ways but no seem to work for the first issue replacing text creating the regex we can achieve.

Can you please do basic example of how to set it out? how to find drk1wi and replace with hulapolowashed

from this we can see and work out appropriate way to set our the targetrule.
