### ISSUE TITLE
Modlishka unknown certificate issue

### ISSUE THREAD

**Issue by Srilankastyle** [drk1wi/Modlishka#242]
Hi, 
I installed modlishka on a fresh jnstalled kali Linux 2020.4 using the wiki guide and watching a video. 
The installation went smoothly without any problems the only time when I was wondering was when the certificate was created and the codes were already written in the main file so no need to add them again. 
I then went ahead and added the certificate to the Firefox browser and gave it full permissions. 
After starting modlishka and inserting the link into Firefox I get asked for the certificate again so I have to go trough advance and accept it manually again. 
After that I select sign in and I have to pass another certificate. 
The problem is that the site is still not trusted by Firefox. 
All I can do is type the email address and from there I'm stuck as I'm unable to select next on the website.
After checking the terminal its repeating the same message till I close Firefox or the website which is:
TLS handshake error from 127.0.0.1:44464: remote error: tls: unknown certificate authority

The whole installation tutorial has been followed tho I'm not able to get the certificate passes to be able to bypass the Google 2fa verification. 

Were am I going wrong or what am I missing other then that the tutorial was perfect and super easy it's just that it seems to be missing an major part for the certification... 

Thank you in advance

**Comment by Srilankastyle** [comment]
Is there anyone who had or still got the same issue.
I can't seem to work it out researched a lot aswell.
Any advice would be much appreciated. 
Thank you

**Comment by aligrt** [comment]
I am facing the same issue,

**Comment by Srilankastyle** [comment]
Make sure you are changing the certificate details in the file even tho it already has details written in there.
Problem is after that you face other issues wich haven't been fixed yet I did a bit of research and it seems like this method is out dated an no one has a solution and the developer isn't responding anymore unfortunately

**Comment by aligrt** [comment]
I have changed certificate details in autcert.go, but the same issue. Yes, you right this method is outdated. But still I am trying to fix this issue.

**Comment by Srilankastyle** [comment]
After you setup everything and start modlishka are there any errors coming up?
Also after that once you open your browser please specify the browser you use!
What is the message when you go to the link from modelishka what does the logo say to the certificate?

**Comment by aligrt** [comment]
**After you setup everything and start modlishka are there any errors coming up?**
It's working fine without error messages.

>>>> "Modlishka" Reverse Proxy started - v.1.1 <<<<
Author: Piotr Duszynski @drk1wi  

Listening on [0.0.0.0:443]
Proxying HTTPS [google.com] via [https://loopback.modlishka.io]
Listening on [0.0.0.0:80]
Proxying HTTP [google.com] via [http://loopback.modlishka.io]

**Also after that once you open your browser please specify the browser you use!**
I am using firefox on Kali 2021

**What is the message when you go to the link from modelishka what does the logo say to the certificate?**
A warning message 

**_Warning: Potential Security Risk Ahead

Firefox detected a potential security threat and did not continue to www.loopback.modlishka.io. If you visit this site, attackers could try to steal information like your passwords, emails, or credit card details.

What can you do about it?

The issue is most likely with the website, and there is nothing you can do to resolve it.

If you are on a corporate network or using anti-virus software, you can reach out to the support teams for assistance. You can also notify the website’s administrator about the problem._**

**Comment by Srilankastyle** [comment]
Okey that's the message I had myself make sure you replace the keys in the auto file even tho it got the keys in it already they are wrong.

Or if you have done that then you forgot to insert the certificate into Firefox to mark it as trusted. 

If you done both of that please leave your telegram or what's app or something for easier communication.

So that we can try to resolve the problem after that aswell

**Comment by aligrt** [comment]
I have done both despite this still facing the same issue. Knock at Telegram @babarbuttgrt

**Comment by kmac48** [comment]
any fix?

**Comment by JimmyDevil** [comment]
do you fix this guys? I have the exact same issue and nothing works...

**Comment by Chuks6608** [comment]
Maybe change your browser
