### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by ssl-user-en** [drk1wi/Modlishka#253]
I'm trying to compile the tool with some changes. Getting this error. Can anyone please help?

make                                                                                                        2 ⨯
go test -v main.go main_test.go
main.go:18:2: cannot find package "." in:
        /usr/share/go-1.15/src/vendor/github.com/drk1wi/Modlishka/config
main.go:19:2: cannot find package "." in:
        /usr/share/go-1.15/src/vendor/github.com/drk1wi/Modlishka/core
main.go:20:2: cannot find package "." in:
        /usr/share/go-1.15/src/vendor/github.com/drk1wi/Modlishka/log
main.go:21:2: cannot find package "." in:
        /usr/share/go-1.15/src/vendor/github.com/drk1wi/Modlishka/plugin
main.go:22:2: cannot find package "." in:
        /usr/share/go-1.15/src/vendor/github.com/drk1wi/Modlishka/runtime
make: *** [Makefile:23: test] Error 1

**Comment by Cyber-Warrior-6** [comment]
yes bro i am also getting the same error

**Comment by equation-group** [comment]
This error is because your go version is old.  
First- uninstall your existing go version from  /usr/local/src and /usr/local/bin .
Bin maybe not get deleted because it is locked, so you've to release it first, then also modify or reset .bashrc

install latest version of Golang from official site, see installation instructions.
then follow the steps and install modlishka, check ired.team blog post on how to install and generate certificate using certbot letsencrypt.
then you can start using it, use tmux to run it in background.

The reverse proxy won't work on google, discord (integrity issue) you need to manually modify and overwrite, create custom build of modlishka.

**Comment by TomAbel** [comment]
cannot find package "." - you are missing  vendored copies of dependencies 
do `go mod vendor`

**Comment by sonu13579** [comment]
.
