### ISSUE TITLE
Google template - Can't get it working with push notifications

### ISSUE THREAD

**Issue by riflon** [drk1wi/Modlishka#34]
Hello!. First I want to congratulate you because this is an amazing tool.
I tested it with google and seems to work really well with 2FA using SMS. However I was not able to get it working with push notifications. I'm always getting a timeout error.
Did you test it with push notifications?
Maybe i'm doing something wrong but I tested almost everything and i'm always getting the timeout error.

Let me know if you have any comments about this.

Thank you again and keep rocking.

**Comment by drk1wi** [comment]
Hi, Thank you :-) 

I have checked and the issue with push notifications and the issue is that it based on obfuscated JS code:

trace: Error: Bad hint: failed sanity: m;/_/scs/apps-static/_/js/k=oz.gapi.en.2lYDMsSK54U.O/am=wQ/rt=j/d=1/rs=AGLTcCMymAizLmRiAlJ4_BDLaoYc2P1-ag/m=__features__

A JS patch is needed in this case and can be applied through the -rules parameter.

**Comment by riflon** [comment]
Hi!
Thanks man. I supposed that but I wasn't sure. I'll take a deep look at it.
Thank you for your fast reply, I really appreciate it.

**Comment by drk1wi** [comment]
if you find a way, a pull request would be appreciated to the config file :-)  thanks.

**Comment by riflon** [comment]
Yes sure!!!! I'll work on it and I'll let you know if I find a solution. Thanks again!
