### ISSUE TITLE
N0 user name captured but instead a password

### ISSUE THREAD

**Issue by tehseensagar** [drk1wi/Modlishka#90]
Greetings @drk1wi ,

I would like to thanks for such a nice tool. Well I'm having little issues with it and I could not find any answers of it as well.

I'm using google.com and I change the url from google to gmail.com .

Issue No-1:
-------------
`http: TLS handshake error from x.x.x.x:32035: EOF`

Issue No-2:
-------------
`Url Param 'users_id' is missing`

When clicking on session tab impersonate user button. nothing happen and in console getting above error message.

How to overcome these above issues . Im using wildcard certificates.

Regards

**Comment by drk1wi** [comment]
Re issue nr.1. Ignore it, it doesn't affect anything. 
Re issue nr.1 you will have to set up your regular expressions for control panel (otherwise grep the log file - everything is there) and use URL/?user_id parameter. Otherwise the tool doesn't know how to track.

Check out the wiki (there's also an example quickstart for gmail).

**Comment by tehseensagar** [comment]
Im closing this thread uuid can be generated manually and add them into url

for example. https://mydmain.com/?ident=uuid-sefl-generated

you may use site like https://uuidgenerator.net
