### ISSUE TITLE
account block facebook using modlishka

### ISSUE THREAD

**Issue by tehseensagar** [drk1wi/Modlishka#91]
Greetings to all,

During test I encounter account block issue on facebook , my two test account blocked when testing it on modlishka . Even on some id I didnt get any username / password for facebook. But on google account I do get password but not user name. I thing this tool need some serious testing and bug fixing. I've been testing it for 4 days and facing different kind of issues. but these name not shown and blocking account is really bad . I dont thing so I could carry out Phishing attack on site during pentest if it block client account this will be pain in ass.

Regards

**Comment by drk1wi** [comment]
Hi, Thanks for you feedback. I think that you are trying to rely your pentest results on the 'control' plugin, which isn't part of the core. If you want to catch usernames and display them on the webpage, you will have to create a right regex, otherwise all of the passwords/logins are in the log file.

The tool has been tested and I have been using if in many pentests sucessfully for the past year, but it's not a point and click set up with automatic password greping ;-) 

Re: facebook, I guess all of the website will be implementing different types of security measures against reverse proxies. There's always a way to set the tool to support them.

**Comment by tehseensagar** [comment]
Well have you tested it with facebook can you share your config. so I may test it. Ive tried wlidcard regex but failed. Looking forward for your kind response.

**Comment by drk1wi** [comment]
I am sorry, but creating a config file for your penetration test is outside of the scope of support for this tool. If you have any particular bug to report, please do. At the moment regular expressions and config files are working fine.

**Comment by tehseensagar** [comment]
@drk1wi  well I just asking for a hint where to look into to get this done by myself. Off-course I will share it with community as well .

**Comment by drk1wi** [comment]
closing as resolved. if you have managed to resolve this issue, please create a pull request :-)

**Comment by bamaplumbcrazy** [comment]
Try Facebook ++ download

**Comment by chiefofcoding** [comment]
email me for quick solution. chieflyx@gmail.com
